//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageIT.MedShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public Nullable<double> Salary { get; set; }
        public System.DateTime JoinDate { get; set; }
    
        public virtual UserTable UserTable { get; set; }
    }
}
