//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManageIT.MedShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellsTable
    {
        public int SellsId { get; set; }
        public int ProductId { get; set; }
        public int ProductLeft { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
    }
}
